import { getHistory } from '../storage.js';
import { getQuestionById } from '../questions/index.js';
import { formatDateTime, fillBlankText } from '../utils.js';

export function getAnswerDetail(record){
  const q=getQuestionById(record&&record.questionId);
  const selectedIndex=Number.isInteger(record&&record.selectedIndex)?record.selectedIndex:null;
  const correctIndex=Number.isInteger(record&&record.correctIndex)?record.correctIndex:(q&&Number.isInteger(q.answer)?q.answer:null);
  const selectedChoice=(q&&Array.isArray(q.choices)&&selectedIndex!==null&&selectedIndex>=0&&selectedIndex<q.choices.length)?q.choices[selectedIndex]:null;
  const correctChoice=(q&&Array.isArray(q.choices)&&correctIndex!==null&&correctIndex>=0&&correctIndex<q.choices.length)?q.choices[correctIndex]:null;
  const question=(q&&q.question)||'';
  const passage=(q&&q.passage)||'';
  const sentenceWithMistake=fillBlankText(question,selectedChoice);
  const sentenceWithCorrectAnswer=fillBlankText(question,correctChoice);
  return {questionId:String((record&&record.questionId)||'unknown'),part:(record&&record.part)||((q&&q.part)||null),difficulty:(record&&record.difficulty)||((q&&q.difficulty)||'unknown'),tags:Array.isArray(record&&record.tags)?record.tags:((q&&q.tags)||[]),category:(q&&q.category)||null,question,passage,choices:(q&&Array.isArray(q.choices))?q.choices:[],selectedIndex,selectedChoice,correctIndex,correctChoice,mistakenWord:selectedChoice,correctWord:correctChoice,sentenceWithMistake,sentenceWithCorrectAnswer,isCorrect:Boolean(record&&record.isCorrect),explanation:(q&&q.explanation)||'',answeredAt:(record&&record.answeredAt)||null};
}
export function getMistakenWordInfo(answerDetail){ if(!answerDetail||typeof answerDetail!=='object')return null; const selectedIndex=Number.isInteger(answerDetail.selectedIndex)?answerDetail.selectedIndex:null; const correctIndex=Number.isInteger(answerDetail.correctIndex)?answerDetail.correctIndex:null; const selectedChoice=('selectedChoice' in answerDetail)?answerDetail.selectedChoice:null; const correctChoice=('correctChoice' in answerDetail)?answerDetail.correctChoice:null; const mistakenWord=selectedChoice===null?null:selectedChoice; const correctWord=correctChoice===null?null:correctChoice; return {questionId:String(answerDetail.questionId||'unknown'),part:answerDetail.part??null,category:answerDetail.category||null,tags:Array.isArray(answerDetail.tags)?answerDetail.tags:[],difficulty:answerDetail.difficulty||'unknown',mistakenWord,correctWord,selectedIndex,correctIndex,selectedLabel:selectedIndex===null?null:String.fromCharCode(65+selectedIndex),correctLabel:correctIndex===null?null:String.fromCharCode(65+correctIndex),selectedChoice,correctChoice,originalQuestion:answerDetail.question||'',sentenceWithMistake:fillBlankText(answerDetail.question||'',selectedChoice),sentenceWithCorrectAnswer:fillBlankText(answerDetail.question||'',correctChoice),passageWithMistake:fillBlankText(answerDetail.passage||'',selectedChoice),passageWithCorrectAnswer:fillBlankText(answerDetail.passage||'',correctChoice),explanation:answerDetail.explanation||'',answeredAt:formatDateTime(answerDetail.answeredAt)}; }
export function getMistakenWordSummary(limit=50){ return getWrongQuestionDetails(limit).map((x)=>getMistakenWordInfo(x)).filter(Boolean); }
export function getWrongWordPatternSummary(){ const rows=getMistakenWordSummary(200); const out={totalWrongAnswers:rows.length,mistakenWords:{},correctWords:{},mistakenToCorrectPairs:{},byCategory:{},byTag:{}}; const add=(obj,key)=>{const k=String(key);obj[k]=(obj[k]||0)+1;}; rows.forEach((x)=>{ const mistaken=x.selectedChoice===null?'未選択':String(x.selectedChoice); const correct=x.correctChoice===null?'不明':String(x.correctChoice); add(out.mistakenWords,mistaken); add(out.correctWords,correct); add(out.mistakenToCorrectPairs,`${mistaken} => ${correct}`); add(out.byCategory,x.category||'unknown'); (Array.isArray(x.tags)?x.tags:[]).forEach((t)=>add(out.byTag,t||'unknown')); }); return out; }
export function getQuestionPerformanceStats(){ const map={}; getHistory().forEach((r)=>{ const d=getAnswerDetail(r); if(!map[d.questionId]) map[d.questionId]={questionId:d.questionId,part:d.part,difficulty:d.difficulty,tags:d.tags,category:d.category,question:d.question,passage:d.passage,choices:d.choices,explanation:d.explanation,totalAttempts:0,correctCount:0,wrongCount:0,accuracy:0,lastAnsweredAt:null}; const x=map[d.questionId]; x.totalAttempts++; if(d.isCorrect)x.correctCount++; else x.wrongCount++; if(!x.lastAnsweredAt||new Date(d.answeredAt)>new Date(x.lastAnsweredAt))x.lastAnsweredAt=d.answeredAt; x.accuracy=x.totalAttempts?Math.round(x.correctCount/x.totalAttempts*100):0; }); return Object.values(map); }
export function getAnswerDetailsByQuestionId(questionId){return getHistory().filter((x)=>x.questionId===String(questionId)).map(getAnswerDetail).sort((a,b)=>new Date(b.answeredAt)-new Date(a.answeredAt));}
export function getLatestWrongAnswerDetail(questionId){return getAnswerDetailsByQuestionId(questionId).find((x)=>!x.isCorrect)||null;}
export function getLatestCorrectAnswerDetail(questionId){return getAnswerDetailsByQuestionId(questionId).find((x)=>x.isCorrect)||null;}
export function enrichPerformanceWithAnswerExamples(performance){ const rows=getAnswerDetailsByQuestionId(performance.questionId); return {...performance,latestWrongAnswer:getLatestWrongAnswerDetail(performance.questionId),latestCorrectAnswer:getLatestCorrectAnswerDetail(performance.questionId),recentAnswers:rows.slice(0,5)}; }
export function getWrongQuestionDetails(limit=20){return getHistory().filter((x)=>!x.isCorrect).slice(-limit).reverse().map(getAnswerDetail);}
export function getCorrectQuestionDetails(limit=20){return getHistory().filter((x)=>x.isCorrect).slice(-limit).reverse().map(getAnswerDetail);}
export function getWeakQuestionDetails(limit=20){return getQuestionPerformanceStats().filter((x)=>x.wrongCount>=1&&x.accuracy<80).sort((a,b)=>b.wrongCount-a.wrongCount||a.accuracy-b.accuracy).slice(0,limit).map(enrichPerformanceWithAnswerExamples);}
export function getStrongQuestionDetails(limit=20){return getQuestionPerformanceStats().filter((x)=>x.totalAttempts>=1&&x.accuracy>=80).sort((a,b)=>b.correctCount-a.correctCount||b.accuracy-a.accuracy).slice(0,limit).map(enrichPerformanceWithAnswerExamples);}
export function countBy(arr){const m={};arr.forEach((x)=>{const k=String(x||'unknown');m[k]=(m[k]||0)+1;});return m;}
export function formatAnswerSummaryForPrompt(a,opt){if(!a)return null;const o={isCorrect:a.isCorrect,answeredAt:formatDateTime(a.answeredAt)};if(opt.includeChoices){o.selected={index:a.selectedIndex,label:a.selectedIndex===null?null:String.fromCharCode(65+a.selectedIndex),text:a.selectedChoice};o.correct={index:a.correctIndex,label:a.correctIndex===null?null:String.fromCharCode(65+a.correctIndex),text:a.correctChoice};}else{o.selectedIndex=a.selectedIndex;o.correctIndex=a.correctIndex;}return o;}
export function formatPerformanceDetailForPrompt(item,opt){const b={questionId:item.questionId,part:item.part,difficulty:item.difficulty,tags:item.tags,category:item.category,totalAttempts:item.totalAttempts,correctCount:item.correctCount,wrongCount:item.wrongCount,accuracy:item.accuracy,lastAnsweredAt:formatDateTime(item.lastAnsweredAt),latestWrongAnswer:formatAnswerSummaryForPrompt(item.latestWrongAnswer,opt),latestCorrectAnswer:formatAnswerSummaryForPrompt(item.latestCorrectAnswer,opt),recentAnswers:(item.recentAnswers||[]).slice(0,5).map((x)=>formatAnswerSummaryForPrompt(x,opt))};if(opt.includeQp){b.question=item.question;b.passage=item.passage;}if(opt.includeChoices){b.choices={A:item.choices&&item.choices[0]||null,B:item.choices&&item.choices[1]||null,C:item.choices&&item.choices[2]||null,D:item.choices&&item.choices[3]||null};}if(opt.includeExp)b.explanation=item.explanation;return b;}
export function getMistakePatternSummary(){ const wrong=getWrongQuestionDetails(200); const performance=getQuestionPerformanceStats(); const choicePatterns={}; wrong.forEach((x)=>{const key=`${x.selectedChoice||'null'} => ${x.correctChoice||'null'}`;choicePatterns[key]=(choicePatterns[key]||0)+1;}); const wrongById=performance.filter((x)=>x.wrongCount>0).sort((a,b)=>b.wrongCount-a.wrongCount).slice(0,10).map((x)=>({questionId:x.questionId,wrongCount:x.wrongCount,accuracy:x.accuracy})); const typeAgg={}; performance.forEach((x)=>{if(x.wrongCount<1)return;const k=`part${x.part}/${x.category||'unknown'}/${x.difficulty}`;typeAgg[k]=(typeAgg[k]||0)+x.wrongCount;}); return {totalWrongAnswers:wrong.length,wrongByPart:countBy(wrong.map((x)=>x.part)),wrongByTag:countBy(wrong.flatMap((x)=>x.tags||[])),wrongByDifficulty:countBy(wrong.map((x)=>x.difficulty)),wrongByCategory:countBy(wrong.map((x)=>x.category||'unknown')),choiceConfusionPatterns:choicePatterns,frequentlyWrongQuestionIds:wrongById,frequentlyWrongQuestionTypes:Object.entries(typeAgg).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([type,count])=>({type,count}))}; }
export function getStrengthPatternSummary(){ const correct=getCorrectQuestionDetails(200); const strong=getStrongQuestionDetails(50); const stableTypes={}; strong.forEach((x)=>{const k=`part${x.part}/${x.category||'unknown'}/${x.difficulty}`;stableTypes[k]=(stableTypes[k]||0)+x.correctCount;}); return {totalCorrectAnswers:correct.length,correctByPart:countBy(correct.map((x)=>x.part)),correctByTag:countBy(correct.flatMap((x)=>x.tags||[])),correctByDifficulty:countBy(correct.map((x)=>x.difficulty)),correctByCategory:countBy(correct.map((x)=>x.category||'unknown')),highAccuracyQuestionIds:strong.slice(0,10).map((x)=>({questionId:x.questionId,accuracy:x.accuracy,correctCount:x.correctCount,totalAttempts:x.totalAttempts})),stableStrongQuestionTypes:Object.entries(stableTypes).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([type,count])=>({type,count}))}; }
