import { QUESTION_DATA, getQuestionById } from './questions/index.js';
import { escapeHtml, pad2, formatDuration, formatDateTime, shuffle, fillBlankText } from './utils.js';
import { getHistory, saveHistory, getMistakes, saveMistakes, getSessions, saveSessions, getSettings, saveSettings, closeStaleSessions } from './storage.js';
import { calculateOverallStats, calculatePartStats, calculateTagStats, calculateDifficultyStats, calculateSessionStats, getUnfinishedQuestionsFromSessions, calculateTodaySummary, getRecommendedAction } from './engine/statsEngine.js';
import { createSession, saveNewSession, finalizeSession, recordAnswerToSessionAndHistory } from './engine/sessionEngine.js';
import { getAnswerDetail, getWrongQuestionDetails, getCorrectQuestionDetails, getWeakQuestionDetails, getStrongQuestionDetails, formatPerformanceDetailForPrompt, getMistakePatternSummary, getStrengthPatternSummary, getMistakenWordSummary, getWrongWordPatternSummary } from './ai/analysisData.js';
import { getDefaultAiPromptOptions, aiOptionsFromUI, buildAiPrompt, genPrompt, copyAiPrompt } from './ai/promptBuilder.js';
import { state } from './state.js';



const LISTENING_DATA = [
  { id:'P1-001',part:1,category:'photograph',difficulty:'easy',tags:['写真描写','リスニング','会議'],imageDescription:'A woman is arranging documents on a conference table.',visualPrompt:'会議室のテーブルで女性が書類を整理している場面',audioText:'A. A woman is arranging documents on a conference table. B. A woman is opening a window. C. A man is writing on a whiteboard. D. Several people are leaving the room.',question:'写真を最もよく表している文を選んでください。',choices:['A woman is arranging documents on a conference table.','A woman is opening a window.','A man is writing on a whiteboard.','Several people are leaving the room.'],answer:0,explanation:'女性が書類を整理している描写が中心です。'},
  { id:'P1-002',part:1,category:'photograph',difficulty:'easy',tags:['写真描写','リスニング','受付'],imageDescription:'Two visitors are speaking with a receptionist at the front desk.',visualPrompt:'受付で来訪者2名がスタッフと会話している場面',audioText:'A. Two visitors are speaking with a receptionist. B. A courier is carrying boxes upstairs. C. A clerk is cleaning the hallway. D. A customer is checking out at a supermarket.',question:'写真を最もよく表している文を選んでください。',choices:['Two visitors are speaking with a receptionist.','A courier is carrying boxes upstairs.','A clerk is cleaning the hallway.','A customer is checking out at a supermarket.'],answer:0,explanation:'受付で来訪者対応をしている場面です。'},
  { id:'P1-003',part:1,category:'photograph',difficulty:'medium',tags:['写真描写','リスニング','メンテナンス'],imageDescription:'A technician is inspecting an air-conditioning unit on a ladder.',visualPrompt:'技術者が脚立で空調設備を点検している場面',audioText:'A. A technician is inspecting an air-conditioning unit. B. Workers are painting a parking lot. C. A manager is giving a speech on stage. D. Employees are eating in a cafeteria.',question:'写真を最もよく表している文を選んでください。',choices:['A technician is inspecting an air-conditioning unit.','Workers are painting a parking lot.','A manager is giving a speech on stage.','Employees are eating in a cafeteria.'],answer:0,explanation:'空調設備の点検作業に一致します。'},
  { id:'P2-001',part:2,category:'question-response',difficulty:'easy',tags:['応答問題','資料提出'],audioText:'Where should I leave these documents?',question:'音声に対する最も自然な応答を選んでください。',choices:["On the manager's desk, please.",'Yes, I read them yesterday.','It starts at nine.','No, I do not have a car.'],answer:0,explanation:'Where に対して場所で答えています。'},
  { id:'P2-002',part:2,category:'question-response',difficulty:'easy',tags:['応答問題','会議'],audioText:'Did the client confirm tomorrow\'s meeting?',question:'音声に対する最も自然な応答を選んでください。',choices:['Yes, she sent an email this morning.','At the third floor conference room.','Because the train was delayed.','I prefer coffee to tea.'],answer:0,explanation:'Did への自然なYes応答です。'},
  { id:'P2-003',part:2,category:'question-response',difficulty:'medium',tags:['応答問題','出張'],audioText:'When will you submit your travel report?',question:'音声に対する最も自然な応答を選んでください。',choices:['By Friday afternoon.','At the airport counter.','With my department manager.','For three business days.'],answer:0,explanation:'When なので時を答えます。'},
  { id:'P2-004',part:2,category:'question-response',difficulty:'medium',tags:['応答問題','商品発送'],audioText:'Who is handling the shipment to Osaka?',question:'音声に対する最も自然な応答を選んでください。',choices:['Ken from logistics is in charge of it.','It left from gate number six.','Around ten boxes were delivered.','The invoice number is on the label.'],answer:0,explanation:'Who に対して担当者を答えます。'},
  { id:'P2-005',part:2,category:'question-response',difficulty:'medium',tags:['応答問題','イベント案内'],audioText:'Could you remind me where the training room is?',question:'音声に対する最も自然な応答を選んでください。',choices:['Sure, it is next to the cafeteria.','Yes, it begins at 2 p.m.','No, I already printed it.','I will call you yesterday.'],answer:0,explanation:'場所を尋ねる依頼への自然な応答です。'},
  { id:'P3-001-Q1',groupId:'P3-001',part:3,category:'conversation',difficulty:'medium',tags:['会話問題','予定変更'],audioText:'Woman: Hi, Mark. Did you receive the revised meeting agenda? Man: Yes. It looks like the budget discussion was moved to the afternoon. Woman: Right. The finance manager cannot join in the morning.',question:'What are the speakers mainly discussing?',choices:['A revised meeting schedule','A new office location','A delayed shipment','A customer complaint'],answer:0,explanation:'議題の時間変更についてです。'},
  { id:'P3-001-Q2',groupId:'P3-001',part:3,category:'conversation',difficulty:'medium',tags:['会話問題','予定変更'],audioText:'Woman: Hi, Mark. Did you receive the revised meeting agenda? Man: Yes. It looks like the budget discussion was moved to the afternoon. Woman: Right. The finance manager cannot join in the morning.',question:'Why was the budget discussion moved?',choices:['The finance manager is unavailable in the morning','The meeting room is under maintenance','The client requested an online call','The presenter missed the train'],answer:0,explanation:'財務マネージャーが午前参加不可だからです。'},
  { id:'P3-002-Q1',groupId:'P3-002',part:3,category:'conversation',difficulty:'medium',tags:['会話問題','顧客対応'],audioText:'Man: We received a complaint about late delivery. Woman: I checked it. The package was held at the transfer center. Man: Let us call the customer and offer expedited shipping.',question:'What problem are the speakers discussing?',choices:['A late delivery','A broken printer','A missing invoice','A canceled event'],answer:0,explanation:'配送遅延クレームが話題です。'},
  { id:'P3-002-Q2',groupId:'P3-002',part:3,category:'conversation',difficulty:'medium',tags:['会話問題','顧客対応'],audioText:'Man: We received a complaint about late delivery. Woman: I checked it. The package was held at the transfer center. Man: Let us call the customer and offer expedited shipping.',question:'What will the speakers do next?',choices:['Contact the customer','Close the warehouse','Change product prices','Hire new staff'],answer:0,explanation:'顧客へ連絡すると述べています。'},
  { id:'P3-003-Q1',groupId:'P3-003',part:3,category:'conversation',difficulty:'hard',tags:['会話問題','社内研修'],audioText:'Woman: Are you attending the compliance workshop this afternoon? Man: I planned to, but I have to finish the quarterly report. Woman: Then join the make-up session on Friday morning.',question:'Why can the man not attend this afternoon?',choices:['He must finish a report','He is on a business trip','He lost his ID card','He has a client dinner'],answer:0,explanation:'四半期レポート作成が理由です。'},
  { id:'P3-003-Q2',groupId:'P3-003',part:3,category:'conversation',difficulty:'hard',tags:['会話問題','社内研修'],audioText:'Woman: Are you attending the compliance workshop this afternoon? Man: I planned to, but I have to finish the quarterly report. Woman: Then join the make-up session on Friday morning.',question:'What does the woman suggest?',choices:['Attend a make-up session','Ask for remote work','Skip the workshop','Submit the report today'],answer:0,explanation:'金曜午前の振替参加を提案しています。'},
  { id:'P4-001-Q1',groupId:'P4-001',part:4,category:'announcement',difficulty:'medium',tags:['説明文問題','メンテナンス'],audioText:'Good morning. Due to maintenance work, the east entrance will be closed from 9 a.m. to noon today. Please use the main entrance during this time.',question:'Why will the east entrance be closed?',choices:['Because of maintenance work','Because of a company event','Because of bad weather','Because of a delivery delay'],answer:0,explanation:'理由が明示されています。'},
  { id:'P4-001-Q2',groupId:'P4-001',part:4,category:'announcement',difficulty:'medium',tags:['説明文問題','メンテナンス'],audioText:'Good morning. Due to maintenance work, the east entrance will be closed from 9 a.m. to noon today. Please use the main entrance during this time.',question:'When should people use the main entrance?',choices:['From 9 a.m. to noon','Only after noon','All day tomorrow','Before 8 a.m.'],answer:0,explanation:'時間帯指定があります。'},
  { id:'P4-002-Q1',groupId:'P4-002',part:4,category:'talk',difficulty:'medium',tags:['説明文問題','イベント案内'],audioText:'Thank you for visiting City Expo Hall. The product seminar will begin at 2 p.m. in Room B. Registered guests can pick up materials at the reception desk.',question:'What event is being announced?',choices:['A product seminar','A safety drill','A hiring interview','A store closing sale'],answer:0,explanation:'製品セミナーの案内です。'},
  { id:'P4-002-Q2',groupId:'P4-002',part:4,category:'talk',difficulty:'medium',tags:['説明文問題','イベント案内'],audioText:'Thank you for visiting City Expo Hall. The product seminar will begin at 2 p.m. in Room B. Registered guests can pick up materials at the reception desk.',question:'Where can guests get materials?',choices:['At the reception desk','In Room A','At the parking office','On the second floor cafe'],answer:0,explanation:'受付で受け取ると述べています。'},
  { id:'P4-003-Q1',groupId:'P4-003',part:4,category:'recorded-message',difficulty:'hard',tags:['説明文問題','店舗案内'],audioText:'Welcome to Greenmart customer service. Our downtown branch is open until 8 p.m. on weekdays and 6 p.m. on Saturdays. For order status, press 2 after the tone.',question:'What is mentioned about the downtown branch?',choices:['It closes at 8 p.m. on weekdays','It opens at 6 a.m. every day','It is closed on Fridays','It has moved to a new location'],answer:0,explanation:'平日20時まで営業です。'},
  { id:'P4-003-Q2',groupId:'P4-003',part:4,category:'recorded-message',difficulty:'hard',tags:['説明文問題','店舗案内'],audioText:'Welcome to Greenmart customer service. Our downtown branch is open until 8 p.m. on weekdays and 6 p.m. on Saturdays. For order status, press 2 after the tone.',question:'What should callers do to check order status?',choices:['Press 2','Press 5','Visit the branch','Send a fax'],answer:0,explanation:'order status は2番です。'}
];


const ALL_QUESTIONS=[...LISTENING_DATA,...QUESTION_DATA];
const qMap = Object.fromEntries(ALL_QUESTIONS.map((q) => [q.id, q]));
function getByMode(mode){if(mode==='all')return shuffle(QUESTION_DATA);if(mode==='random')return shuffle(ALL_QUESTIONS);if(mode==='listening')return shuffle(LISTENING_DATA);if(mode==='miniMock'){const pick=(part,n,src)=>shuffle(src.filter(q=>q.part===part)).slice(0,n);return [...pick(1,3,LISTENING_DATA),...pick(2,5,LISTENING_DATA),...pick(3,6,LISTENING_DATA),...pick(4,6,LISTENING_DATA),...pick(5,10,QUESTION_DATA),...pick(6,5,QUESTION_DATA),...pick(7,5,QUESTION_DATA)];}if(mode==='mistake'){const set=new Set(getMistakes());return ALL_QUESTIONS.filter((q)=>set.has(q.id));}if(mode.startsWith('part'))return ALL_QUESTIONS.filter((q)=>q.part===Number(mode.slice(4)));return[];}
function getStatsForAi(){return{overall:calculateOverallStats(),parts:calculatePartStats(),tags:calculateTagStats(),diffs:calculateDifficultyStats(),sessions:calculateSessionStats(),history:getHistory(),mistakes:getMistakes(),unfinished:getUnfinishedQuestionsFromSessions()};}


function getListeningQuestionsByPart(part){return LISTENING_DATA.filter(q=>q.part===part);}
function stopSpeaking(){if(window.speechSynthesis)window.speechSynthesis.cancel();}
function speakText(text){state.audioUnsupported='';if(!('speechSynthesis' in window)||typeof SpeechSynthesisUtterance==='undefined'){state.audioUnsupported='この環境では音声読み上げに対応していません';render();return;}stopSpeaking();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=0.95;u.pitch=1.0;window.speechSynthesis.speak(u);}
function toggleTranscript(){state.transcriptVisible=!state.transcriptVisible;render();}
function renderAudioControls(text){return `<div class='row'><button class='p' onclick='speakText(${JSON.stringify('')}+${JSON.stringify('')}+\`${'${escapeHtml(text)}'}\`)'>音声を再生</button><button class='g' onclick='stopSpeaking()'>停止</button><button class='g' onclick='toggleTranscript()'>スクリプト${state.transcriptVisible?'非表示':'表示'}</button></div>`;}

function statusJa(s){return s==='completed'?'完了':(s==='abandoned'?'途中終了':'進行中');}
function start(mode){stopSpeaking();clearTimeout(state.timer);state.transcriptVisible=false;const qs=getByMode(mode);if(!qs.length){state.screen='empty';state.emptyTitle=mode==='mistake'?'苦手復習':'対象問題がありません';state.emptyBody=mode==='mistake'?'復習対象はありません。間違えた問題がここに表示されます。':'対象問題がありません。';return render();}state.questions=qs;state.i=0;state.selected=null;state.answered=false;state.result=false;state.quizMessage='';state.showExplanation=state.settings.autoShowExplanation;state.sessionResults=[];state.session = saveNewSession(createSession(mode, qs));state.screen='quiz';render();}
function answer(){if(state.screen!=='quiz'||state.answered)return;if(state.selected===null){state.quizMessage='選択肢を選んでから回答してください。';render();return;}const q=state.questions[state.i];const ok=state.selected===q.answer;state.answered=true;state.result=ok;state.quizMessage='';const result = recordAnswerToSessionAndHistory(state.session, q, state.selected, ok, state.session.mode);state.session = result.session;state.sessionResults.push({questionId:q.id,part:q.part,isCorrect:ok});if(state.settings.autoNext){clearTimeout(state.timer);state.timer=setTimeout(()=>nextQ(true),state.settings.autoNextDelayMs);}render();setTimeout(()=>document.getElementById('nextBtn')?.focus(),20);}
function nextQ(fromTimer=false){if(!state.answered)return;if(!fromTimer)clearTimeout(state.timer);if(state.i<state.questions.length-1){stopSpeaking();state.i++;state.selected=null;state.answered=false;state.quizMessage='';state.showExplanation=state.settings.autoShowExplanation;render();return;}clearTimeout(state.timer);state.session=finalizeSession(state.session,'completed');state.screen='result';render();}
function backHome(abandon=true){stopSpeaking();clearTimeout(state.timer);if(abandon&&state.screen==='quiz'&&state.session&&state.session.status==='in_progress')state.session=finalizeSession(state.session,'abandoned');state.screen='home';render();}
function resetHistory(){if(!confirm('学習履歴・苦手問題・セッション記録をすべて削除します。よろしいですか？'))return;saveHistory([]);saveMistakes([]);saveSessions([]);state.aiMessage='履歴をリセットしました';render();}
function renderAiPromptBuilder(){
const d=getDefaultAiPromptOptions();
return `<div class='card'><h2>AI分析プロンプト作成</h2>
<h3>1. 基本統計</h3><label><input type='checkbox' id='cb_summary' ${d.summary?'checked':''}>全体サマリー</label><label><input type='checkbox' id='cb_part' ${d.part?'checked':''}>Part別正答率</label><label><input type='checkbox' id='cb_tags' ${d.tags?'checked':''}>タグ別正答率</label><label><input type='checkbox' id='cb_diff' ${d.diff?'checked':''}>難易度別正答率</label>
<h3>2. 問題詳細</h3><label><input type='checkbox' id='cb_wrong' ${d.wrong?'checked':''}>直近で間違えた問題の詳細</label><label><input type='checkbox' id='cb_correctDetails' ${d.correctDetails?'checked':''}>直近で正解した問題の詳細</label><label><input type='checkbox' id='cb_weakDetails' ${d.weakDetails?'checked':''}>苦手問題の詳細</label><label><input type='checkbox' id='cb_strongDetails' ${d.strongDetails?'checked':''}>得意問題の詳細</label>
<div class='grid g2'><label>間違えた問題詳細の件数<input type='number' id='wrongLimit' min='1' max='100' value='20'></label><label>正解した問題詳細の件数<input type='number' id='correctLimit' min='1' max='100' value='10'></label><label>苦手問題詳細の件数<input type='number' id='weakLimit' min='1' max='100' value='20'></label><label>得意問題詳細の件数<input type='number' id='strongLimit' min='1' max='100' value='10'></label></div>
	<h3>3. 傾向分析</h3><label><input type='checkbox' id='cb_mistakeSummary' ${d.mistakeSummary?'checked':''}>間違い傾向サマリー</label><label><input type='checkbox' id='cb_strengthSummary' ${d.strengthSummary?'checked':''}>得意傾向サマリー</label><label><input type='checkbox' id='cb_choicePattern' ${d.choicePattern?'checked':''}>選択肢の誤答パターン</label><label><input type='checkbox' id='cb_mistakenWordList' ${d.mistakenWordList?'checked':''}>間違えた単語・正解単語一覧</label><label><input type='checkbox' id='cb_wrongWordPattern' ${d.wrongWordPattern?'checked':''}>間違えた単語パターン</label><label><input type='checkbox' id='cb_includeFilledSentences' ${d.includeFilledSentences?'checked':''}>誤答文と正解文を含める</label><p class='muted'>「間違えた単語・正解単語一覧」をONにすると、選んだ選択肢と正解選択肢を比較して、どの単語・表現を間違えたかをAIに渡せます。</p>
<h3>4. セッション情報</h3><label><input type='checkbox' id='cb_completed'>完了セッション一覧</label><label><input type='checkbox' id='cb_abandoned'>途中終了セッション一覧</label><label><input type='checkbox' id='cb_unanswered'>未回答で終わった問題一覧</label><label><input type='checkbox' id='cb_time' ${d.time?'checked':''}>学習時間サマリー</label><label><input type='checkbox' id='cb_recent50'>直近50件の回答履歴</label><label><input type='checkbox' id='cb_recent10'>直近10件の回答履歴</label><label><input type='checkbox' id='cb_weak'>苦手問題リスト(旧)</label>
<h3>5. 出力オプション</h3><label><input type='checkbox' id='cb_includeQp' ${d.includeQp?'checked':''}>問題文・本文を含める</label><label><input type='checkbox' id='cb_includeChoices' ${d.includeChoices?'checked':''}>選択肢を含める</label><label><input type='checkbox' id='cb_includeExp' ${d.includeExp?'checked':''}>解説を含める</label><label><input type='checkbox' id='cb_request' ${d.request?'checked':''}>AIへの依頼文</label>
<div class='row' style='margin-top:10px;'><button class='p' onclick='genPrompt()'>再生成</button><button class='g' onclick='copyAiPrompt()'>プロンプトをコピー</button><button class='g' onclick="state.screen='history';render()">学習履歴へ戻る</button><button class='g' onclick='backHome(false)'>ホームへ戻る</button></div><p id='copyMsg' class='muted'>${escapeHtml(state.aiMessage)}</p><textarea id='promptArea'>${escapeHtml(state.aiPromptText)}</textarea></div>`;}
function render(){const app=document.getElementById('app');const ov=calculateOverallStats();if(state.screen==='home'){const today=calculateTodaySummary();app.innerHTML=`<div class='card'><h2>学習サマリー</h2><div class='grid g4'><div class='sum'><strong>${ov.total}</strong><span>総回答数</span></div><div class='sum'><strong>${ov.rate}%</strong><span>正答率</span></div><div class='sum'><strong>${ov.mistakes}</strong><span>苦手問題</span></div><div class='sum'><strong>${calculateSessionStats().abandoned.length}</strong><span>途中終了</span></div></div></div><div class='card'><h2>今日の学習サマリー</h2><div class='grid g4'><div class='sum'><strong>${today.answers}</strong><span>今日の回答数</span></div><div class='sum'><strong>${today.correct}</strong><span>今日の正解数</span></div><div class='sum'><strong>${today.rate}%</strong><span>今日の正答率</span></div><div class='sum'><strong>${formatDuration(today.timeSec)}</strong><span>今日の学習時間</span></div></div></div><div class='card'><h2>おすすめアクション</h2><div class='passage'>${escapeHtml(getRecommendedAction())}</div></div><div class='card'><h2>演習を開始</h2><div class='grid g2'><button class='p' onclick="start('miniMock')">ミニ模試</button><button class='p' onclick="start('listening')">Listening練習</button><button class='p' onclick="start('part1')">Part 1演習</button><button class='p' onclick="start('part2')">Part 2演習</button><button class='p' onclick="start('part3')">Part 3演習</button><button class='p' onclick="start('part4')">Part 4演習</button><button class='p' onclick="start('part5')">Part 5演習</button><button class='p' onclick="start('part6')">Part 6演習</button><button class='p' onclick="start('part7')">Part 7演習</button><button class='p' onclick="start('random')">ランダム演習</button><button class='p' onclick="start('all')">全部モード</button><button class='p' onclick="start('mistake')">苦手復習</button></div><div class='row' style='margin-top:10px;'><button class='g' onclick="state.screen='history';render()">学習履歴</button></div></div>`;return;}
if(state.screen==='empty'){app.innerHTML=`<div class='card'><h2>${escapeHtml(state.emptyTitle)}</h2><p>${escapeHtml(state.emptyBody)}</p><button class='g' onclick='backHome(false)'>ホームへ戻る</button></div>`;return;}
if(state.screen==='quiz'){const q=state.questions[state.i];const ratio=Math.round((state.i+1)/state.questions.length*100);app.innerHTML=`<div class='card'><p>${state.i+1} / ${state.questions.length}</p><div class='bar'><div class='fill' style='width:${ratio}%'></div></div><div style='margin-top:8px'><span class='badge bp'>Part ${escapeHtml(q.part)}</span><span class='badge bd'>${escapeHtml(q.difficulty)}</span>${q.tags.map((t)=>`<span class='badge bt'>${escapeHtml(t)}</span>`).join('')}</div>${q.part<=4&&q.visualPrompt?`<div class='passage'><b>写真説明カード</b><br>${escapeHtml(q.visualPrompt)}<br><span class='muted'>${escapeHtml(q.imageDescription||'')}</span></div>`:''}<p><b>${escapeHtml(q.question)}</b></p>${q.part<=4?`<div class='row'><button class='p' onclick='_playCurrent()'>音声を再生</button><button class='g' onclick='stopSpeaking()'>停止</button><button class='g' onclick='toggleTranscript()'>スクリプト${state.transcriptVisible?'非表示':'表示'}</button></div>${state.transcriptVisible?`<div class='passage'>${escapeHtml(q.audioText||'')}</div>`:''}${state.audioUnsupported?`<p class='msg warnm'>${escapeHtml(state.audioUnsupported)}</p>`:''}`:''}${q.passage?`<div class='passage'>${escapeHtml(q.passage)}</div>`:''}<div class='choices'>${q.choices.map((c,idx)=>{let cls='choice';if(state.selected===idx)cls+=' sel';if(state.answered){if(idx===q.answer)cls+=' ok';if(idx===state.selected&&idx!==q.answer)cls+=' ng';}return `<button class='${cls}' ${state.answered?'disabled':''} onclick='state.selected=${idx};state.quizMessage="";render()'>${String.fromCharCode(65+idx)}. ${escapeHtml(c)}</button>`;}).join('')}</div>${state.quizMessage?`<p class='msg warnm'>${escapeHtml(state.quizMessage)}</p>`:''}<div class='row' style='margin-top:10px;'><button class='p' onclick='answer()' ${state.answered?'disabled':''}>回答する (Enter)</button><button class='g' onclick='backHome(true)'>ホームへ戻る (Esc)</button></div>${state.answered?`<p class='msg ${state.result?'okm':'ngm'}'>${state.result?'正解です':'不正解です'}</p><label><input type='checkbox' ${state.showExplanation?'checked':''} onchange='state.showExplanation=this.checked;render()'>解説を表示する</label>${state.showExplanation?`<div class='passage'>${escapeHtml(q.explanation)}</div>`:''}<button id='nextBtn' class='p' onclick='nextQ(false)'>次へ (Enter)</button>`:''}</div><div class='card'><h3>設定</h3><label><input type='checkbox' ${state.settings.autoShowExplanation?'checked':''} onchange='state.settings.autoShowExplanation=this.checked;saveSettings(state.settings)'>解説を自動表示する</label><label><input type='checkbox' ${state.settings.autoNext?'checked':''} onchange='state.settings.autoNext=this.checked;saveSettings(state.settings)'>回答後に自動で次へ進む</label></div>`;return;}
if(state.screen==='result'){const rec=state.sessionResults;const totalQ=state.session.totalQuestions,answered=state.session.answeredCount,correct=state.session.correctCount,un=Math.max(0,totalQ-answered),rate=answered?Math.round(correct/answered*100):0;const partRows=[1,2,3,4,5,6,7].map((p)=>{const r=rec.filter((x)=>x.part===p);const c=r.filter((x)=>x.isCorrect).length;return`<p>Part ${p}: ${c} / ${r.length} 正解 ${r.length?Math.round(c/r.length*100):0}%</p>`;}).join('');const wrongRows=rec.filter((x)=>!x.isCorrect).map((x)=>`<li>${escapeHtml(x.questionId)} - ${escapeHtml((qMap[x.questionId]&&qMap[x.questionId].question)||'unknown')}</li>`).join('')||'<li>なし</li>';app.innerHTML=`<div class='card'><h2>結果</h2><p>今回の出題数: ${totalQ}</p><p>今回の回答数: ${answered}</p><p>今回の正解数: ${correct}</p><p>今回の正答率: ${rate}%</p><p>未回答数: ${un}</p>${(()=>{const l=rec.filter(x=>x.part<=4),r=rec.filter(x=>x.part>=5);const lc=l.filter(x=>x.isCorrect).length,rc=r.filter(x=>x.isCorrect).length;return `<p>Listening正答率: ${l.length?Math.round(lc/l.length*100):0}%</p><p>Reading正答率: ${r.length?Math.round(rc/r.length*100):0}%</p>`;})()}<h3>Part別正答率</h3>${partRows}<h3>間違えた問題一覧</h3><ul>${wrongRows}</ul><div class='row'><button class='p' onclick='backHome(false)'>ホームへ戻る</button><button class='g' onclick='start(state.session.mode)'>同じモードでもう一回</button></div></div>`;return;}
if(state.screen==='history'){const p=calculatePartStats(),tag=calculateTagStats(),d=calculateDifficultyStats(),ss=calculateSessionStats();app.innerHTML=`<div class='card'><h2>学習履歴</h2><div class='grid g4'><div class='sum'><strong>${ov.total}</strong><span>総回答</span></div><div class='sum'><strong>${ov.rate}%</strong><span>正答率</span></div><div class='sum'><strong>${ss.completed.length}</strong><span>完了</span></div><div class='sum'><strong>${ss.abandoned.length}</strong><span>途中終了</span></div></div><p>合計学習時間: ${formatDuration(ss.totalSec)} / 平均学習時間: ${formatDuration(ss.avgSec)}</p><h3>Part別正答率</h3>${ov.total===0?'<p class="muted">履歴がまだありません。</p>':p.map((x)=>`<p>Part ${x.part}: ${x.correct}/${x.total} (${x.rate}%)</p>`).join('')}<h3>タグ別正答率 上位/下位</h3>${tag.length===0?'<p class="muted">履歴がまだありません。</p>':`${tag.slice(0,3).map((x)=>`<p>下位 ${escapeHtml(x.tag)}: ${x.rate}%</p>`).join('')}${tag.slice(-3).map((x)=>`<p>上位 ${escapeHtml(x.tag)}: ${x.rate}%</p>`).join('')}`}<h3>難易度別正答率</h3>${ov.total===0?'<p class="muted">履歴がまだありません。</p>':d.map((x)=>`<p>${escapeHtml(x.difficulty)}: ${x.correct}/${x.total} (${x.rate}%)</p>`).join('')}<div class='row'><button class='p' onclick="state.screen='ai';state.aiPromptText=buildAiPrompt(getDefaultAiPromptOptions());render()">AI分析プロンプト作成</button><button class='d' onclick='resetHistory()'>履歴リセット</button><button class='g' onclick='backHome(false)'>ホームへ戻る</button></div></div><div class='card'><h3>直近セッション一覧</h3>${ss.recent.length===0?'<p class="muted">履歴がまだありません。</p>':ss.recent.map((x)=>`<div class='session-card'><p>開始日時: ${escapeHtml(formatDateTime(x.startedAt))}</p><p>モード: ${escapeHtml(x.mode)}</p><p>status: ${escapeHtml(statusJa(x.status))}</p><p>回答済み数 / 全問題数: ${x.answeredCount} / ${x.totalQuestions}</p><p>正答率: ${x.accuracy}%</p><p>未回答数: ${x.unansweredCount}</p><p>学習時間: ${formatDuration(x.durationSeconds)}</p></div>`).join('')}</div>`;return;}
if(state.screen==='ai'){app.innerHTML=renderAiPromptBuilder();setTimeout(genPrompt,0);}}
window.addEventListener('beforeunload',()=>{if(state.screen==='quiz'&&state.session&&state.session.status==='in_progress')state.session=finalizeSession(state.session,'abandoned');});
document.addEventListener('keydown',(e)=>{if(state.screen!=='quiz')return;const m={a:0,b:1,c:2,d:3};const k=e.key.toLowerCase();if(k in m&&!state.answered){state.selected=m[k];state.quizMessage='';render();}if(e.key==='Enter'){e.preventDefault();state.answered?nextQ(false):answer();}if(e.key==='Escape'){e.preventDefault();backHome(true);}});
function initApp(){state.settings=getSettings();state.showExplanation=state.settings.autoShowExplanation;closeStaleSessions();render();}
window.state=state;window.saveSettings=saveSettings;window.buildAiPrompt=buildAiPrompt;window.getDefaultAiPromptOptions=getDefaultAiPromptOptions;window._playCurrent=()=>speakText((state.questions[state.i]&&state.questions[state.i].audioText)||'');window.start=start;window.speakText=speakText;window.stopSpeaking=stopSpeaking;window.toggleTranscript=toggleTranscript;window.render=render;window.answer=answer;window.nextQ=nextQ;window.backHome=backHome;window.genPrompt=genPrompt;window.copyAiPrompt=copyAiPrompt;window.resetHistory=resetHistory;
initApp();
